<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="0" name="Failed suite [Surefire suite]">
  <test name="Surefire test">
    <classes>
      <class name="com.cadence.cos.AddCookiesTest"/>
      <class name="com.cadence.cos.CopyOfPrintTest"/>
      <class name="com.cadence.cos.ExceptionTest"/>
      <class name="com.cadence.cos.ParallelMethodTest"/>
      <class name="com.cadence.cos.PrintTest"/>
      <class name="com.cadence.cos.RemoveCookiesTest"/>
    </classes>
  </test> <!-- Surefire test -->
  <test name="Surefire test(failed)">
    <classes>
      <class name="com.cadence.cos.ExceptionTest">
        <methods>
          <include name="divisionWithException"/>
        </methods>
      </class> <!-- com.cadence.cos.ExceptionTest -->
      <class name="com.cadence.cos.ParallelMethodTest">
        <methods>
          <include name="afterMethod"/>
          <include name="beforeMethod"/>
        </methods>
      </class> <!-- com.cadence.cos.ParallelMethodTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
